$(function(){
    $('.banner').DB_tabMotionBanner({
        key:'b28551',
        autoRollingTime:6000,                            
        bgSpeed:500,
        motion:{
            DB_1_1:{left:-500,opacity:0,speed:1000,delay:500},
            DB_1_2:{top:50,opacity:0,speed:1000,delay:1500},
            DB_1_3:{left:400,opacity:0,speed:1000,delay:1000},        
            DB_2_1:{left:-500,opacity:0,speed:1000,delay:500},
            DB_2_2:{left:400,opacity:0,speed:1000,delay:1000},
            DB_2_3:{top:50,opacity:0,speed:1000,delay:1500},       
            DB_3_1:{left:-500,opacity:0,speed:1000,delay:500},
            DB_3_2:{left:400,opacity:0,speed:1000,delay:1000},         
            end:null
        }
    })
    $('.navig').hover(function(){
        $('.comboBox:nth-child(' + ($(this).index() + 1) + ')').stop().slideDown(200);
    },function(){
        $('.comboBox:nth-child(' + ($(this).index() + 1) + ')').stop().slideUp(200);
    })
    $('.comboBox').hover(function(){
        $(this).stop().show();
    },function(){
        $(this).stop().slideUp(200);
    })
    $('.product_list ul li').hover(function(){
        $(this).find('.float_layer').css('display',"block");
    },function(){
        $(this).find('.float_layer').css('display',"none");
    })
    $('.float_layer').hover(function(){
        $(this).css('display',"block");
    },function(){
        $(this).css('display',"block");
    })
    $(".news_box").kinMaxShow({
        height:280,
        button:{
            switchEvent:'click',
            showIndex:false,
            normal:{width:'25px',height:'5px',left:'595px',bottom:'7px',opacity:0.8,background:"#C7C7C7",marginRight:'6px',border:"none"},
            focus:{background:"#C28E34",border:"none"}
            }		
    })
    $(".all").click(function(){
        $('.research_cont1').css('display','block');
        $('.research_cont2').css('display','none');
        $('.research_cont3').css('display','none');
        $(this).css('color','#C28E34');
        $('.school').css('color','#505050');
        $('.analyse').css('color','#505050');
    })
    $(".school").click(function(){
        $('.research_cont2').css('display','block');
        $('.research_cont1').css('display','none');
        $('.research_cont3').css('display','none');
        $(this).css('color','#C28E34');
        $('.all').css('color','#505050');
        $('.analyse').css('color','#505050');
    })
    $(".analyse").click(function(){
        $('.research_cont3').css('display','block');
        $('.research_cont2').css('display','none');
        $('.research_cont1').css('display','none');
        $(this).css('color','#C28E34');
        $('.school').css('color','#505050');
        $('.all').css('color','#505050');
    })
    $('.dowebok').liMarquee();
})